/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/witch/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="mesh_char_040" geometry={nodes.mesh_char_040.geometry} material={materials._039_Witch} morphTargetDictionary={nodes.mesh_char_040.morphTargetDictionary} morphTargetInfluences={nodes.mesh_char_040.morphTargetInfluences} scale={100} />
    </group>
  )
}

useGLTF.preload('/model.glb')
