// Persian

export const letters = [
  {
    name: "alef",
    character: {
      isolated: "آ",
      initial: "ا",
      medial: "ـا",
      final: "ـا",
    },
    transliteration: "a",
    pronunciation: "Alef",
    joins: false,
  },
  {
    name: "be",
    character: {
      isolated: "ب",
      initial: "بـ",
      medial: "ـبـ",
      final: "ـب",
    },
    transliteration: "b",
    pronunciation: "Be",
    joins: true,
  },
  {
    name: "pe",
    character: {
      isolated: "پ",
      initial: "پـ",
      medial: "ـپـ",
      final: "ـپ",
    },
    transliteration: "p",
    pronunciation: "Pe",
    joins: true,
  },
  {
    name: "te",
    character: {
      isolated: "ت",
      initial: "تـ",
      medial: "ـتـ",
      final: "ـت",
    },
    transliteration: "t",
    pronunciation: "Te",
    joins: true,
  },
  {
    name: "se",
    character: {
      isolated: "ث",
      initial: "ثـ",
      medial: "ـثـ",
      final: "ـث",
    },
    transliteration: "s",
    pronunciation: "Se",
    joins: true,
  },
  {
    name: "jim",
    character: {
      isolated: "ج",
      initial: "جـ",
      medial: "ـجـ",
      final: "ـج",
    },
    transliteration: "j",
    pronunciation: "Jim",
    joins: true,
  },
  {
    name: "che",
    character: {
      isolated: "چ",
      initial: "چـ",
      medial: "ـچـ",
      final: "ـچ",
    },
    transliteration: "ch",
    pronunciation: "Che",
    joins: true,
  },
  {
    name: "he_jimi",
    character: {
      isolated: "ح",
      initial: "حـ",
      medial: "ـحـ",
      final: "ـح",
    },
    transliteration: "h",
    pronunciation: "He Jimi",
    joins: true,
  },
  {
    name: "khe",
    character: {
      isolated: "خ",
      initial: "خـ",
      medial: "ـخـ",
      final: "ـخ",
    },
    transliteration: "kh",
    pronunciation: "Khe",
    joins: true,
  },
  {
    name: "dal",
    character: {
      isolated: "د",
      initial: "د",
      medial: "ـد",
      final: "ـد",
    },
    transliteration: "d",
    pronunciation: "Dal",
    joins: false,
  },
  {
    name: "zal",
    character: {
      isolated: "ذ",
      initial: "ذ",
      medial: "ـذ",
      final: "ـذ",
    },
    transliteration: "z",
    pronunciation: "Zal",
    joins: false,
  },
  {
    name: "re",
    character: {
      isolated: "ر",
      initial: "ر",
      medial: "ـر",
      final: "ـر",
    },
    transliteration: "r",
    pronunciation: "Re",
    joins: false,
  },
  {
    name: "ze",
    character: {
      isolated: "ز",
      initial: "ز",
      medial: "ـز",
      final: "ـز",
    },
    transliteration: "z",
    pronunciation: "Ze",
    joins: false,
  },
  {
    name: "zhe",
    character: {
      isolated: "ژ",
      initial: "ژ",
      medial: "ـژ",
      final: "ـژ",
    },
    transliteration: "zh",
    pronunciation: "Zhe",
    joins: false,
  },
  {
    name: "sin",
    character: {
      isolated: "س",
      initial: "سـ",
      medial: "ـسـ",
      final: "ـس",
    },
    transliteration: "s",
    pronunciation: "Sin",
    joins: true,
  },
  {
    name: "shin",
    character: {
      isolated: "ش",
      initial: "شـ",
      medial: "ـشـ",
      final: "ـش",
    },
    transliteration: "sh",
    pronunciation: "Shin",
    joins: true,
  },
  {
    name: "sad",
    character: {
      isolated: "ص",
      initial: "صـ",
      medial: "ـصـ",
      final: "ـص",
    },
    transliteration: "s",
    pronunciation: "Sad",
    joins: true,
  },
  {
    name: "zad",
    character: {
      isolated: "ض",
      initial: "ضـ",
      medial: "ـضـ",
      final: "ـض",
    },
    transliteration: "z",
    pronunciation: "Zad",
    joins: true,
  },
  {
    name: "ta",
    character: {
      isolated: "ط",
      initial: "طـ",
      medial: "ـطـ",
      final: "ـط",
    },
    transliteration: "t",
    pronunciation: "Ta",
    joins: true,
  },
  {
    name: "za",
    character: {
      isolated: "ظ",
      initial: "ظـ",
      medial: "ـظـ",
      final: "ـظ",
    },
    transliteration: "z",
    pronunciation: "Za",
    joins: true,
  },
  {
    name: "ein",
    character: {
      isolated: "ع",
      initial: "عـ",
      medial: "ـعـ",
      final: "ـع",
    },
    transliteration: "'",
    pronunciation: "Ein",
    joins: true,
  },
  {
    name: "ghein",
    character: {
      isolated: "غ",
      initial: "غـ",
      medial: "ـغـ",
      final: "ـغ",
    },
    transliteration: "gh",
    pronunciation: "Ghein",
    joins: true,
  },
  {
    name: "fe",
    character: {
      isolated: "ف",
      initial: "فـ",
      medial: "ـفـ",
      final: "ـف",
    },
    transliteration: "f",
    pronunciation: "Fe",
    joins: true,
  },
  {
    name: "ghaf",
    character: {
      isolated: "ق",
      initial: "قـ",
      medial: "ـقـ",
      final: "ـق",
    },
    transliteration: "q",
    pronunciation: "Ghaf",
    joins: true,
  },
  {
    name: "kaf",
    character: {
      isolated: "ک",
      initial: "کـ",
      medial: "ـکـ",
      final: "ـک",
    },
    transliteration: "k",
    pronunciation: "Kaf",
    joins: true,
  },
  {
    name: "gaf",
    character: {
      isolated: "گ",
      initial: "گـ",
      medial: "ـگـ",
      final: "ـگ",
    },
    transliteration: "g",
    pronunciation: "Gaf",
    joins: true,
  },
  {
    name: "lam",
    character: {
      isolated: "ل",
      initial: "لـ",
      medial: "ـلـ",
      final: "ـل",
    },
    transliteration: "l",
    pronunciation: "Lam",
    joins: true,
  },
  {
    name: "mim",
    character: {
      isolated: "م",
      initial: "مـ",
      medial: "ـمـ",
      final: "ـم",
    },
    transliteration: "m",
    pronunciation: "Mim",
    joins: true,
  },
  {
    name: "noon",
    character: {
      isolated: "ن",
      initial: "نـ",
      medial: "ـنـ",
      final: "ـن",
    },
    transliteration: "n",
    pronunciation: "Noon",
    joins: true,
  },
  {
    name: "vav",
    character: {
      isolated: "و",
      initial: "و",
      medial: "ـو",
      final: "ـو",
    },
    transliteration: "v",
    pronunciation: "Vav",
    joins: false,
  },
  {
    name: "he",
    character: {
      isolated: "ه",
      initial: "هـ",
      medial: "ـهـ",
      final: "ـه",
    },
    transliteration: "h",
    pronunciation: "He",
    joins: true,
  },
  {
    name: "ye",
    character: {
      isolated: "ی",
      initial: "یـ",
      medial: "ـیـ",
      final: "ـی",
    },
    transliteration: "y",
    pronunciation: "Ye",
    joins: true,
  },
];

// English

/* 

export const letters = [
  {
    name: "alef",
    character: {
      isolated: "ا",
      initial: "ا",
      medial: "ـا",
      final: "ـا",
    },
    transliteration: "a",
    pronunciation: "Alef",
    joins: false,
  },
  {
    name: "be",
    character: {
      isolated: "ب",
      initial: "بـ",
      medial: "ـبـ",
      final: "ـب",
    },
    transliteration: "b",
    pronunciation: "Be",
    joins: true,
  },
  {
    name: "pe",
    character: {
      isolated: "پ",
      initial: "پـ",
      medial: "ـپـ",
      final: "ـپ",
    },
    transliteration: "p",
    pronunciation: "Pe",
    joins: true,
  },
  {
    name: "te",
    character: {
      isolated: "ت",
      initial: "تـ",
      medial: "ـتـ",
      final: "ـت",
    },
    transliteration: "t",
    pronunciation: "Te",
    joins: true,
  },
  {
    name: "se",
    character: {
      isolated: "ث",
      initial: "ثـ",
      medial: "ـثـ",
      final: "ـث",
    },
    transliteration: "s",
    pronunciation: "Se",
    joins: true,
  },
  {
    name: "jim",
    character: {
      isolated: "ج",
      initial: "جـ",
      medial: "ـجـ",
      final: "ـج",
    },
    transliteration: "j",
    pronunciation: "Jim",
    joins: true,
  },
  {
    name: "che",
    character: {
      isolated: "چ",
      initial: "چـ",
      medial: "ـچـ",
      final: "ـچ",
    },
    transliteration: "ch",
    pronunciation: "Che",
    joins: true,
  },
  {
    name: "he_jimi",
    character: {
      isolated: "ح",
      initial: "حـ",
      medial: "ـحـ",
      final: "ـح",
    },
    transliteration: "h",
    pronunciation: "He Jimi",
    joins: true,
  },
  {
    name: "khe",
    character: {
      isolated: "خ",
      initial: "خـ",
      medial: "ـخـ",
      final: "ـخ",
    },
    transliteration: "kh",
    pronunciation: "Khe",
    joins: true,
  },
  {
    name: "dal",
    character: {
      isolated: "د",
      initial: "د",
      medial: "ـد",
      final: "ـد",
    },
    transliteration: "d",
    pronunciation: "Dal",
    joins: false,
  },
  {
    name: "zal",
    character: {
      isolated: "ذ",
      initial: "ذ",
      medial: "ـذ",
      final: "ـذ",
    },
    transliteration: "z",
    pronunciation: "Zal",
    joins: false,
  },
  {
    name: "re",
    character: {
      isolated: "ر",
      initial: "ر",
      medial: "ـر",
      final: "ـر",
    },
    transliteration: "r",
    pronunciation: "Re",
    joins: false,
  },
  {
    name: "ze",
    character: {
      isolated: "ز",
      initial: "ز",
      medial: "ـز",
      final: "ـز",
    },
    transliteration: "z",
    pronunciation: "Ze",
    joins: false,
  },
  {
    name: "zhe",
    character: {
      isolated: "ژ",
      initial: "ژ",
      medial: "ـژ",
      final: "ـژ",
    },
    transliteration: "zh",
    pronunciation: "Zhe",
    joins: false,
  },
  {
    name: "sin",
    character: {
      isolated: "س",
      initial: "سـ",
      medial: "ـسـ",
      final: "ـس",
    },
    transliteration: "s",
    pronunciation: "Sin",
    joins: true,
  },
  {
    name: "shin",
    character: {
      isolated: "ش",
      initial: "شـ",
      medial: "ـشـ",
      final: "ـش",
    },
    transliteration: "sh",
    pronunciation: "Shin",
    joins: true,
  },
  {
    name: "sad",
    character: {
      isolated: "ص",
      initial: "صـ",
      medial: "ـصـ",
      final: "ـص",
    },
    transliteration: "s",
    pronunciation: "Sad",
    joins: true,
  },
  {
    name: "zad",
    character: {
      isolated: "ض",
      initial: "ضـ",
      medial: "ـضـ",
      final: "ـض",
    },
    transliteration: "z",
    pronunciation: "Zad",
    joins: true,
  },
  {
    name: "ta",
    character: {
      isolated: "ط",
      initial: "طـ",
      medial: "ـطـ",
      final: "ـط",
    },
    transliteration: "t",
    pronunciation: "Ta",
    joins: true,
  },
  {
    name: "za",
    character: {
      isolated: "ظ",
      initial: "ظـ",
      medial: "ـظـ",
      final: "ـظ",
    },
    transliteration: "z",
    pronunciation: "Za",
    joins: true,
  },
  {
    name: "ein",
    character: {
      isolated: "ع",
      initial: "عـ",
      medial: "ـعـ",
      final: "ـع",
    },
    transliteration: "'",
    pronunciation: "Ein",
    joins: true,
  },
  {
    name: "ghein",
    character: {
      isolated: "غ",
      initial: "غـ",
      medial: "ـغـ",
      final: "ـغ",
    },
    transliteration: "gh",
    pronunciation: "Ghein",
    joins: true,
  },
  {
    name: "fe",
    character: {
      isolated: "ف",
      initial: "فـ",
      medial: "ـفـ",
      final: "ـف",
    },
    transliteration: "f",
    pronunciation: "Fe",
    joins: true,
  },
  {
    name: "ghaf",
    character: {
      isolated: "ق",
      initial: "قـ",
      medial: "ـقـ",
      final: "ـق",
    },
    transliteration: "q",
    pronunciation: "Ghaf",
    joins: true,
  },
  {
    name: "kaf",
    character: {
      isolated: "ک",
      initial: "کـ",
      medial: "ـکـ",
      final: "ـک",
    },
    transliteration: "k",
    pronunciation: "Kaf",
    joins: true,
  },
  {
    name: "gaf",
    character: {
      isolated: "گ",
      initial: "گـ",
      medial: "ـگـ",
      final: "ـگ",
    },
    transliteration: "g",
    pronunciation: "Gaf",
    joins: true,
  },
  {
    name: "lam",
    character: {
      isolated: "ل",
      initial: "لـ",
      medial: "ـلـ",
      final: "ـل",
    },
    transliteration: "l",
    pronunciation: "Lam",
    joins: true,
  },
  {
    name: "mim",
    character: {
      isolated: "م",
      initial: "مـ",
      medial: "ـمـ",
      final: "ـم",
    },
    transliteration: "m",
    pronunciation: "Mim",
    joins: true,
  },
  {
    name: "noon",
    character: {
      isolated: "ن",
      initial: "نـ",
      medial: "ـنـ",
      final: "ـن",
    },
    transliteration: "n",
    pronunciation: "Noon",
    joins: true,
  },
  {
    name: "vav",
    character: {
      isolated: "و",
      initial: "و",
      medial: "ـو",
      final: "ـو",
    },
    transliteration: "v",
    pronunciation: "Vav",
    joins: false,
  },
  {
    name: "he",
    character: {
      isolated: "ه",
      initial: "هـ",
      medial: "ـهـ",
      final: "ـه",
    },
    transliteration: "h",
    pronunciation: "He",
    joins: true,
  },
  {
    name: "ye",
    character: {
      isolated: "ی",
      initial: "یـ",
      medial: "ـیـ",
      final: "ـی",
    },
    transliteration: "y",
    pronunciation: "Ye",
    joins: true,
  },
];
*/
